name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build WAR file
      run: mvn --batch-mode --update-snapshots verify -f pom.xml
      # optional: use 'run: mvn test' to run tests

    - name: Login to container registry
      uses: docker/login-action@v2
      with:
        #registry: hub.docker.com
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t bearla/eadca2-app .

    - name: Push docker Image
      run: docker push bearla/eadca2-app:latest
      #run: |
      #  docker build -t bearla/eadca2-app:latest .
      #  docker push bearla/eadca2-app:latest
      #uses: docker/build-push-action@v2
      #with:
      #  context: .
      #  file: ./Dockerfile
      #  push: true
      #  tags: bearla/eadca2-app:latest

    - name: Update service manifest
      run: sed -i "s/bprestws:latest/bearla\/eadca2-app:latest/" create-service-manifest.yaml

    - name: Publish YAML artifact
      uses: docker/metadata-action@v3
      with:
        images: bearla/eadca2-app:latest
        manifest-file: create-service-manifest.yaml
      # optional: use 'uses: actions/upload-artifact@v2' to upload the YAML artifact
